// news by category actions
export const GET_NEWS_CATEGORY_BEGIN = "GET_NEWS_CATEGORY_BEGIN";
export const GET_NEWS_CATEGORY_GENERAL_SUCCESS =
  "GET_NEWS_CATEGORY_GENERAL_SUCCESS";
export const GET_NEWS_CATEGORY_HEALTH_SUCCESS =
  "GET_NEWS_CATEGORY_HEALTH_SUCCESS";
export const GET_NEWS_CATEGORY_BUSINESS_SUCCESS =
  "GET_NEWS_CATEGORY_BUSINESS_SUCCESS";
export const GET_NEWS_CATEGORY_SCIENCE_SUCCESS =
  "GET_NEWS_CATEGORY_SCIENCE_SUCCESS";
export const GET_NEWS_CATEGORY_SPORT_SUCCESS =
  "GET_NEWS_CATEGORY_SPORT_SUCCESS";
export const GET_NEWS_CATEGORY_TECHNOLOGY_SUCCESS =
  "GET_NEWS_CATEGORY_TECHNOLOGY_SUCCESS";
export const GET_NEWS_CATEGORY_ERROR = "GET_NEWS_CATEGORY_ERROR";
export const SORT_LATEST_NEWS = "SORT_LATEST_NEWS";
export const GET_NEWS_ARRAY = "GET_NEWS_ARRAY";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";

// mobile layout actions
export const IS_MOBILE_LAYOUT = "IS_MOBILE_LAYOUT";
export const TOGGLE_COMP = "TOGGLE_COMP";
export const IS_SIDEBAR_OPEN = "IS_SIDEBAR_OPEN";
