// news by category actions
export const GET_NEWS_CATEGORY_BEGIN = "GET_NEWS_CATEGORY_BEGIN";
export const GET_NEWS_CATEGORY_SUCCESS = "GET_NEWS_CATEGORY_SUCCESS";
export const GET_NEWS_CATEGORY_ERROR = "GET_NEWS_CATEGORY_ERROR";
export const SORT_LATEST_NEWS = "SORT_LATEST_NEWS";
export const GET_NEWS_ARRAY = "GET_NEWS_ARRAY";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const CLEAN_FAVORITES = "CLEAN_FAVORTIES";
export const REMOVE_DUPLICATES = "REMOVE_DUPLICATES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

// mobile layout actions
export const IS_MOBILE_LAYOUT = "IS_MOBILE_LAYOUT";
export const TOGGLE_COMP = "TOGGLE_COMP";
export const IS_SIDEBAR_OPEN = "IS_SIDEBAR_OPEN";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
